<?php
if (!defined('ABSPATH')) exit;
$metrics = (array)($dashboard['metrics'] ?? array());
$directions = (array)($dashboard['directions'] ?? array());
$trips = (array)($dashboard['trips'] ?? array());
$exceptions = (array)($dashboard['exceptions'] ?? array());
$changes = (array)($dashboard['changes'] ?? array());
$dashboard_link = static function($tab, $extra = array()) use ($selected_year_id) {
    return add_query_arg(array_merge(array('page'=>'olama-transportation','tab'=>$tab,'academic_year_id'=>$selected_year_id), $extra), admin_url('admin.php'));
};
?>
<div id="olama-operations-dashboard" class="olama-operations-dashboard">
    <header class="olama-dashboard-hero">
        <div class="olama-dashboard-hero-copy"><span class="olama-section-kicker"><?php echo esc_html($translate('Transportation Operations')); ?></span><h2><?php echo esc_html($translate('Transportation Control Center')); ?></h2><p><?php echo esc_html($translate('See pressure, assignment gaps, route readiness, and the next action from one place.')); ?></p></div>
        <div class="olama-dashboard-readiness <?php echo intval($dashboard['readiness'] ?? 0) < 70 ? 'is-warning' : 'is-ready'; ?>"><strong><?php echo intval($dashboard['readiness'] ?? 0); ?>%</strong><span><?php echo esc_html($translate('Operational readiness')); ?></span></div>
        <label class="olama-dashboard-year"><?php echo esc_html($translate('Academic Year')); ?><select class="olama-year-navigation"><?php foreach ($years as $year): ?><option value="<?php echo intval($year->id); ?>" <?php selected($selected_year_id,$year->id); ?>><?php echo esc_html($year->year_name); ?></option><?php endforeach; ?></select></label>
    </header>

    <?php if (!empty($dashboard['report_warning'])): ?><div class="notice notice-warning inline"><p><?php echo esc_html($dashboard['report_warning']); ?></p></div><?php endif; ?>

    <section class="olama-dashboard-kpis" aria-label="<?php echo esc_attr($translate('Operational summary')); ?>">
        <a href="<?php echo esc_url($dashboard_link('reports')); ?>" class="olama-dashboard-kpi"><span class="dashicons dashicons-groups"></span><strong><?php echo intval($metrics['students'] ?? 0); ?></strong><small><?php echo esc_html($translate('Transportation students')); ?></small><em><?php echo intval($metrics['families'] ?? 0); ?> <?php echo esc_html($translate('families')); ?></em></a>
        <a href="<?php echo esc_url($dashboard_link('reports')); ?>" class="olama-dashboard-kpi"><span class="dashicons dashicons-yes-alt"></span><strong><?php echo esc_html(($metrics['arrival_rate'] ?? 0).'%'); ?></strong><small><?php echo esc_html($translate('Arrival assigned')); ?></small><em><?php echo intval($metrics['arrival_assigned'] ?? 0); ?> / <?php echo intval($metrics['students'] ?? 0); ?></em></a>
        <a href="<?php echo esc_url($dashboard_link('reports')); ?>" class="olama-dashboard-kpi"><span class="dashicons dashicons-yes-alt"></span><strong><?php echo esc_html(($metrics['departure_rate'] ?? 0).'%'); ?></strong><small><?php echo esc_html($translate('Departure assigned')); ?></small><em><?php echo intval($metrics['departure_assigned'] ?? 0); ?> / <?php echo intval($metrics['students'] ?? 0); ?></em></a>
        <a href="<?php echo esc_url($dashboard_link('buses')); ?>" class="olama-dashboard-kpi"><span class="dashicons dashicons-car"></span><strong><?php echo intval($metrics['used_buses'] ?? 0); ?> / <?php echo intval($metrics['active_buses'] ?? 0); ?></strong><small><?php echo esc_html($translate('Buses in use')); ?></small><em><?php echo esc_html(($metrics['fleet_utilization'] ?? 0).'% '.$translate('seat utilization')); ?></em></a>
        <a href="<?php echo esc_url($dashboard_link('areas')); ?>" class="olama-dashboard-kpi <?php echo !empty($metrics['over_capacity']) ? 'is-critical' : ''; ?>"><span class="dashicons dashicons-warning"></span><strong><?php echo intval($metrics['over_capacity'] ?? 0); ?></strong><small><?php echo esc_html($translate('Over-capacity trips')); ?></small><em><?php echo intval($metrics['trips'] ?? 0); ?> <?php echo esc_html($translate('active trips')); ?></em></a>
        <a href="<?php echo esc_url($dashboard_link('reports')); ?>" class="olama-dashboard-kpi <?php echo !empty($metrics['unassigned_any']) ? 'is-warning' : ''; ?>"><span class="dashicons dashicons-sos"></span><strong><?php echo intval($metrics['unassigned_any'] ?? 0); ?></strong><small><?php echo esc_html($translate('Students needing assignment')); ?></small><em><?php echo intval($metrics['missing_locations'] ?? 0); ?> <?php echo esc_html($translate('families missing locations')); ?></em></a>
    </section>

    <section class="olama-dashboard-panel olama-dashboard-trip-panel">
        <div class="olama-dashboard-panel-head"><div><span class="olama-section-kicker"><?php echo esc_html($translate('Load + Time + Action')); ?></span><h3><?php echo esc_html($translate('Trip Operations Board')); ?></h3><p><?php echo esc_html($translate('Critical and incomplete trips are shown first. Estimated duration appears after route optimization.')); ?></p></div><a class="button button-primary" href="<?php echo esc_url($dashboard_link('areas')); ?>"><?php echo esc_html($translate('Open trip planning')); ?></a></div>
        <div class="olama-dashboard-trip-filters">
            <div class="olama-dashboard-segmented" role="group" aria-label="<?php echo esc_attr($translate('Direction')); ?>"><button type="button" class="button is-active" data-dashboard-direction="all"><?php echo esc_html($translate('Both')); ?></button><button type="button" class="button" data-dashboard-direction="morning"><?php echo esc_html($translate('Arrival')); ?></button><button type="button" class="button" data-dashboard-direction="afternoon"><?php echo esc_html($translate('Departure')); ?></button></div>
            <select id="olama-dashboard-status" aria-label="<?php echo esc_attr($translate('Status')); ?>"><option value="all"><?php echo esc_html($translate('All statuses')); ?></option><option value="critical"><?php echo esc_html($translate('Critical')); ?></option><option value="incomplete"><?php echo esc_html($translate('Incomplete')); ?></option><option value="stale"><?php echo esc_html($translate('Needs recalculation')); ?></option><option value="long"><?php echo esc_html($translate('Long trip')); ?></option><option value="crowded"><?php echo esc_html($translate('Crowded')); ?></option><option value="ready"><?php echo esc_html($translate('Ready')); ?></option><option value="published"><?php echo esc_html($translate('Published')); ?></option></select>
            <input type="search" id="olama-dashboard-trip-search" placeholder="<?php echo esc_attr($translate('Search trip, bus, area, or staff')); ?>">
        </div>
        <div class="olama-dashboard-table-wrap"><table class="widefat striped olama-dashboard-trip-table"><thead><tr><th><?php echo esc_html($translate('Trip')); ?></th><th><?php echo esc_html($translate('Direction')); ?></th><th><?php echo esc_html($translate('Bus / Round')); ?></th><th><?php echo esc_html($translate('Students / Capacity')); ?></th><th><?php echo esc_html($translate('Load')); ?></th><th><?php echo esc_html($translate('Estimated duration')); ?></th><th><?php echo esc_html($translate('Driver / Companion')); ?></th><th><?php echo esc_html($translate('Status')); ?></th><th><?php echo esc_html($translate('Action')); ?></th></tr></thead><tbody>
        <?php foreach ($trips as $trip): $status=(string)$trip['operational_status']; $search_text=implode(' ',array($trip['name'],$trip['bus_number'],$trip['area_names'],$trip['driver_name'],$trip['companion_name'])); ?>
            <tr data-dashboard-trip data-direction="<?php echo esc_attr($trip['direction']); ?>" data-status="<?php echo esc_attr($status); ?>" data-search="<?php echo esc_attr(strtolower($search_text)); ?>">
                <td><strong><?php echo esc_html($trip['name']); ?></strong><small><?php echo esc_html($trip['area_names'] ?: $translate('No planning areas')); ?></small></td>
                <td><span class="olama-dashboard-direction is-<?php echo esc_attr($trip['direction']); ?>"><?php echo esc_html($trip['direction']==='morning'?$translate('Arrival'):$translate('Departure')); ?></span></td>
                <td><strong><?php echo esc_html($trip['bus_number'] ?: $translate('No bus')); ?></strong><small><?php echo $trip['bus_trip_number'] ? esc_html($translate('Round').' '.$trip['bus_trip_number']) : '—'; ?></small></td>
                <td><strong><?php echo intval($trip['student_count']); ?> / <?php echo $trip['bus_capacity'] ? intval($trip['bus_capacity']) : '—'; ?></strong><small><?php echo intval($trip['family_count']); ?> <?php echo esc_html($translate('families')); ?> · <?php echo $trip['available_seats']===null?'—':intval($trip['available_seats']); ?> <?php echo esc_html($translate('available')); ?></small></td>
                <td><div class="olama-dashboard-load <?php echo !empty($trip['is_over_capacity'])?'is-over':''; ?>"><span style="--load:<?php echo esc_attr(min(100,max(0,(float)$trip['occupancy']))); ?>%"></span></div><strong><?php echo esc_html($trip['occupancy'].'%'); ?></strong></td>
                <td><?php if ($trip['duration_minutes']): ?><strong><?php echo intval($trip['duration_minutes']); ?> <?php echo esc_html($translate('min')); ?></strong><small><?php echo $trip['distance_m']?esc_html(round($trip['distance_m']/1000,1).' km'):''; ?></small><?php else: ?><span class="olama-dashboard-muted"><?php echo esc_html($translate('Not optimized')); ?></span><?php endif; ?></td>
                <td><strong><?php echo esc_html($trip['driver_name'] ?: $translate('Driver missing')); ?></strong><small><?php echo esc_html($trip['companion_name'] ?: $translate('Companion missing')); ?></small></td>
                <td><span class="olama-dashboard-status is-<?php echo esc_attr($status); ?>"><?php $status_labels=array('critical'=>'Critical','incomplete'=>'Incomplete','stale'=>'Needs recalculation','long'=>'Long trip','crowded'=>'Crowded','ready'=>'Ready','published'=>'Published'); echo esc_html($translate($status_labels[$status]??ucfirst($status))); ?></span></td>
                <td><a class="button" href="<?php echo esc_url($dashboard_link('areas',array('trip_id'=>(int)$trip['id'],'direction'=>$trip['direction']))); ?>"><?php echo esc_html($translate('Open')); ?></a></td>
            </tr>
        <?php endforeach; ?>
        <?php if (!$trips): ?><tr class="olama-dashboard-empty"><td colspan="9"><?php echo esc_html($translate('No trips exist for this academic year. Create the first trip to begin planning.')); ?></td></tr><?php endif; ?>
        </tbody></table></div><p id="olama-dashboard-no-results" class="olama-dashboard-empty" hidden><?php echo esc_html($translate('No trips match the selected filters.')); ?></p>
    </section>

    <div class="olama-dashboard-lower-grid">
        <section class="olama-dashboard-panel olama-dashboard-exceptions"><div class="olama-dashboard-panel-head"><div><span class="olama-section-kicker"><?php echo esc_html($translate('Next actions')); ?></span><h3><?php echo esc_html($translate('Exception Inbox')); ?></h3></div><span class="olama-dashboard-count"><?php echo count($exceptions); ?></span></div>
            <?php if ($exceptions): ?><ul><?php foreach ($exceptions as $exception): ?><li class="is-<?php echo esc_attr($exception['severity']); ?>"><span class="dashicons <?php echo $exception['severity']==='critical'?'dashicons-warning':'dashicons-info-outline'; ?>"></span><div><strong><?php echo intval($exception['count']); ?> · <?php echo esc_html($translate($exception['label'])); ?></strong><small><?php echo esc_html($translate($exception['severity']==='critical'?'Resolve before operations':'Review recommended')); ?></small></div><a href="<?php echo esc_url(add_query_arg('academic_year_id',$selected_year_id,$exception['url'])); ?>"><?php echo esc_html($translate('Review')); ?> →</a></li><?php endforeach; ?></ul><?php else: ?><div class="olama-dashboard-all-clear"><span class="dashicons dashicons-yes-alt"></span><strong><?php echo esc_html($translate('No operational exceptions detected.')); ?></strong></div><?php endif; ?>
        </section>
        <section class="olama-dashboard-panel olama-dashboard-directions"><div class="olama-dashboard-panel-head"><div><span class="olama-section-kicker"><?php echo esc_html($translate('Coverage')); ?></span><h3><?php echo esc_html($translate('Arrival vs Departure')); ?></h3></div></div>
            <?php foreach (array('morning'=>$translate('Arrival'),'afternoon'=>$translate('Departure')) as $key=>$label): $item=(array)($directions[$key]??array()); ?><article><div><span class="olama-dashboard-direction is-<?php echo esc_attr($key); ?>"><?php echo esc_html($label); ?></span><strong><?php echo esc_html(($item['rate']??0).'%'); ?></strong></div><div class="olama-dashboard-progress"><span style="--progress:<?php echo esc_attr($item['rate']??0); ?>%"></span></div><dl><div><dt><?php echo esc_html($translate('Assigned')); ?></dt><dd><?php echo intval($item['assigned']??0); ?></dd></div><div><dt><?php echo esc_html($translate('Missing')); ?></dt><dd><?php echo intval($item['missing']??0); ?></dd></div><div><dt><?php echo esc_html($translate('Trips')); ?></dt><dd><?php echo intval($item['trips']??0); ?></dd></div></dl></article><?php endforeach; ?>
        </section>
        <section class="olama-dashboard-panel olama-dashboard-changes"><div class="olama-dashboard-panel-head"><div><span class="olama-section-kicker"><?php echo esc_html($translate('Audit trail')); ?></span><h3><?php echo esc_html($translate('What Changed')); ?></h3></div></div>
            <?php if ($changes): ?><ol><?php foreach ($changes as $change): $time=strtotime(get_date_from_gmt($change['created_at'])); ?><li><span class="olama-dashboard-change-dot"></span><div><strong><?php echo esc_html($change['detail']); ?></strong><small><?php echo esc_html($change['actor']); ?> · <?php echo esc_html(human_time_diff($time,current_time('timestamp')).' '.$translate('ago')); ?></small></div></li><?php endforeach; ?></ol><?php else: ?><p class="olama-dashboard-muted"><?php echo esc_html($translate('No recent transportation changes.')); ?></p><?php endif; ?>
        </section>
    </div>

    <section class="olama-dashboard-quick-actions"><strong><?php echo esc_html($translate('Quick actions')); ?></strong><a class="button button-primary" href="<?php echo esc_url($dashboard_link('areas')); ?>"><?php echo esc_html($translate('Create Trip')); ?></a><a class="button" href="<?php echo esc_url($dashboard_link('family-move')); ?>"><?php echo esc_html($translate('Move families')); ?></a><a class="button" href="<?php echo esc_url($dashboard_link('import')); ?>"><?php echo esc_html($translate('Review locations')); ?></a><a class="button" href="<?php echo esc_url($dashboard_link('routes')); ?>"><?php echo esc_html($translate('Rebuild routes')); ?></a><a class="button" href="<?php echo esc_url($dashboard_link('reports')); ?>"><?php echo esc_html($translate('Assignment gaps')); ?></a></section>
</div>
